#!/bin/bash
JAVA=@thermostat.jdk.home@/bin/java
THERMOSTAT_HOME=@thermostat.home@
LIBS=$THERMOSTAT_HOME/libs
CP="$LIBS/thermostat-storage-mongodb-@project.version@.jar"
CP="$CP:$LIBS/thermostat-storage-core-@project.version@.jar"
CP="$CP:$LIBS/thermostat-shared-config-@project.version@.jar"
CP="$CP:$LIBS/thermostat-common-core-@project.version@.jar"
CP="$CP:$LIBS/thermostat-annotations-@project.version@.jar"
CP="$CP:$LIBS/thermostat-launcher-@project.version@.jar"
CP="$CP:$LIBS/mongo-java-driver-@mongo-driver.version@.jar"
CP="$CP:$LIBS/gson-@gson.version@.jar"
CP="$CP:$LIBS/commons-beanutils-@commons-beanutils.version@.jar"
CP="$CP:$LIBS/commons-logging-@commons-logging.version@.jar"
CP="$CP:@project.build.directory@/thermostat-data-populator-@project.version@.jar"
$JAVA -cp $CP \
  -DTHERMOSTAT_HOME=$THERMOSTAT_HOME \
  -DUSER_THERMOSTAT_HOME=@project.build.directory@ \
  com.redhat.thermostat.dev.populator.Main  \
  $@
