#!/bin/bash
#
# Copyright 2012-2014 Red Hat, Inc.
#
# This file is part of Thermostat.
#
# Thermostat is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2, or (at your
# option) any later version.
#
# Thermostat is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Thermostat; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.
#
# Linking this code with other modules is making a combined work
# based on this code.  Thus, the terms and conditions of the GNU
# General Public License cover the whole combination.
#
# As a special exception, the copyright holders of this code give
# you permission to link this code with independent modules to
# produce an executable, regardless of the license terms of these
# independent modules, and to copy and distribute the resulting
# executable under terms of your choice, provided that you also
# meet, for each linked independent module, the terms and conditions
# of the license of that module.  An independent module is a module
# which is not derived from or based on this code.  If you modify
# this code, you may extend this exception to your version of the
# library, but you are not obligated to do so.  If you do not wish
# to do so, delete this exception statement from your version.
#
#####################################################################
#
if [ "$#" -lt 3 ]; then
  echo "usage: $0 <pidOfTargetJvm> <userNameOfJvmOwner> <ipcConfigFile>" >&2
  exit 1
fi
TARGET_PID="$1"
TARGET_USER="$2"
CONFIG_FILE="$3"

# Source thermostat-ipc-client-common from same directory as this script
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/thermostat-ipc-client-common

# Need tools from the JVM
TOOLS_JAR="${JAVA_HOME}/lib/tools.jar"

# Additional JARs necessary for the agent proxy
CLASSPATH="${CLASSPATH}:${THERMOSTAT_LIBS}/thermostat-common-core-@project.version@.jar"
CLASSPATH="${CLASSPATH}:${THERMOSTAT_LIBS}/thermostat-shared-config-@project.version@.jar"
CLASSPATH="${CLASSPATH}:${THERMOSTAT_LIBS}/thermostat-agent-proxy-server-@project.version@.jar"
CLASSPATH="${CLASSPATH}:${THERMOSTAT_LIBS}/gson-@gson.version@.jar"
CLASSPATH="${TOOLS_JAR}:${CLASSPATH}"

AGENT_PROXY_CLASS="com.redhat.thermostat.agent.proxy.server.AgentProxy"

# Set this to remote debug
if [ x"$THERMOSTAT_DEBUG" != x ] ; then
  DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=1082"
fi

# Start server
CONFIG_FILE_ARG="-DipcConfigFile=${CONFIG_FILE}"
# Drop permissions, if root
if [ "$(id -u)" -eq 0 ]; then
  /bin/su -s /bin/bash -c "${JAVA} -cp ${CLASSPATH} ${CONFIG_FILE_ARG} ${LOGGING_ARGS} ${DEBUG_OPTS} ${AGENT_PROXY_CLASS} ${TARGET_PID}" "${TARGET_USER}"
else
  ${JAVA} -cp ${CLASSPATH} "${CONFIG_FILE_ARG}" ${DEBUG_OPTS} ${LOGGING_ARGS} ${AGENT_PROXY_CLASS} "${TARGET_PID}"
fi
