#!/bin/bash
#
# Copyright 2012 Red Hat, Inc.
#
# This file is part of Thermostat.
#
# Thermostat is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2, or (at your
# option) any later version.
#
# Thermostat is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Thermostat; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.
#
# Linking this code with other modules is making a combined work
# based on this code.  Thus, the terms and conditions of the GNU
# General Public License cover the whole combination.
#
# As a special exception, the copyright holders of this code give
# you permission to link this code with independent modules to
# produce an executable, regardless of the license terms of these
# independent modules, and to copy and distribute the resulting
# executable under terms of your choice, provided that you also
# meet, for each linked independent module, the terms and conditions
# of the license of that module.  An independent module is a module
# which is not derived from or based on this code.  If you modify
# this code, you may extend this exception to your version of the
# library, but you are not obligated to do so.  If you do not wish
# to do so, delete this exception statement from your version.
#
#####################################################################
#
# Some necessary variables.
JAVA_DIR="@java.dir@"
JAVA="@java.home@/bin/java"
JCOMMON_JAR="${JAVA_DIR}/jcommon.jar"
MONGO_JAR="${JAVA_DIR}/mongo.jar"
BSON_JAR="${JAVA_DIR}/bson.jar"
TOOLS_JAR="@java.home@/../lib/tools.jar"
AGENT_CLASSPATH="${JCOMMON_JAR}:${MONGO_JAR}:${BSON_JAR}:${TOOLS_JAR}"
# Find the directory where thermostat is installed.
# Note this will not work if there are symlinks to resolve that
# are not full paths.
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
THERM_DIR=`dirname "$( cd -P "$( dirname "$SOURCE" )" && pwd )"`
# Some other necessary variables.
AGENT_CLASSPATH="${AGENT_CLASSPATH}:${THERM_DIR}/lib/thermostat-agent-@project.version@.jar:${THERM_DIR}/lib/thermostat-common-@project.version@.jar"
AGENT_MAIN="com.redhat.thermostat.agent.Main"

AGENT_ARGS="--local --properties ${THERM_DIR}/config/agent.properties"

function usage {
  echo "Usage:"
  echo "  thermostat-agent <--local|--remote|--cluster>"
}

function run_agent {
  ${JAVA} -cp ${AGENT_CLASSPATH} ${AGENT_MAIN} ${AGENT_ARGS}
}

function run_local {
  AGENT_ARGS="${AGENT_ARGS} --local"
  run_agent
  exit $?
}

function run_remote {
  echo "Remote agent not yet supported."
  exit -1
}

function run_cluster {
  echo "Cluster agent not yet supported."
  exit -1
}

if [ $# != 1 ]; then
  usage
  exit -1
fi

if [ $1 = "--local" ]; then
  run_local
elif [ $1 = "--remote" ]; then
  run_remote
elif [ $1 = "--cluster" ]; then
  run_cluster
else
  usage
  exit -1
fi
