#!/bin/bash
#
# Copyright 2012-2014 Red Hat, Inc.
#
# This file is part of Thermostat.
#
# Thermostat is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2, or (at your
# option) any later version.
#
# Thermostat is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Thermostat; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.
#
# Linking this code with other modules is making a combined work
# based on this code.  Thus, the terms and conditions of the GNU
# General Public License cover the whole combination.
#
# As a special exception, the copyright holders of this code give
# you permission to link this code with independent modules to
# produce an executable, regardless of the license terms of these
# independent modules, and to copy and distribute the resulting
# executable under terms of your choice, provided that you also
# meet, for each linked independent module, the terms and conditions
# of the license of that module.  An independent module is a module
# which is not derived from or based on this code.  If you modify
# this code, you may extend this exception to your version of the
# library, but you are not obligated to do so.  If you do not wish
# to do so, delete this exception statement from your version.
#
#####################################################################
# A script aiding thermostat developers to configure thermostat
# so as to get a working thermostat instance after a development
# build.
# 
# This script calls thermostat-setup with canned input coming from
# file devsetup.input and then copies an appropriate agent.auth
# file into the right place.

# Source thermostat-functions from same directory as this script
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/thermostat-functions

if [ "x$THERMOSTAT_HOME" == "x" ]; then
  THERMOSTAT_HOME=$(_find_thermostat_home)
fi
THERMOSTAT_SETUP="$THERMOSTAT_HOME/bin/thermostat-setup"
DEV_INPUT="$THERMOSTAT_HOME/etc/devsetup.input"
if [ "x$USER_THERMOSTAT_HOME" == "x" ]; then
  USER_THERMOSTAT_HOME="$HOME/.thermostat"
fi

# Call the setup script
$THERMOSTAT_SETUP < $DEV_INPUT
retval=$?

if [ $retval -ne 0 ]; then
  echo "Development setup failed." 1>&2
  exit $retval
fi

# Use example users/roles files:
#  thermostat-users-example.properties
#  thermostat-roles-example.properties
cp -v $THERMOSTAT_HOME/etc/examples/thermostat-users-example.properties $THERMOSTAT_HOME/etc/thermostat-users.properties
cp -v $THERMOSTAT_HOME/etc/examples/thermostat-roles-example.properties $THERMOSTAT_HOME/etc/thermostat-roles.properties
# Use the agent-tester user as defined in thermostat-users-example.properties
echo -e 'username=agent-tester\npassword=tester' > $USER_THERMOSTAT_HOME/etc/agent.auth
