#!/bin/bash
#
# Copyright 2012-2015 Red Hat, Inc.
#
# This file is part of Thermostat.
#
# Thermostat is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2, or (at your
# option) any later version.
#
# Thermostat is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Thermostat; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.
#
# Linking this code with other modules is making a combined work
# based on this code.  Thus, the terms and conditions of the GNU
# General Public License cover the whole combination.
#
# As a special exception, the copyright holders of this code give
# you permission to link this code with independent modules to
# produce an executable, regardless of the license terms of these
# independent modules, and to copy and distribute the resulting
# executable under terms of your choice, provided that you also
# meet, for each linked independent module, the terms and conditions
# of the license of that module.  An independent module is a module
# which is not derived from or based on this code.  If you modify
# this code, you may extend this exception to your version of the
# library, but you are not obligated to do so.  If you do not wish
# to do so, delete this exception statement from your version.
#
#####################################################################

# Source thermostat-common from same directory as this script
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/thermostat-common

# NOTE: The following variables come from the system/user
#       profiles (if any)
#
# THERMOSTAT_EXT_BOOT_CLASSPATH
# THERMOSTAT_EXT_JAVA_OPTS
# THERMOSTAT_EXT_OPTS

# This is the minimal boot classpath thermostat needs. Other dependencies
# will get started by the OSGi framework once that's up.
BOOT_CLASSPATH="${THERMOSTAT_LIBS}/org.apache.felix.framework-@felix.framework.version@.jar"
BOOT_CLASSPATH="${BOOT_CLASSPATH}:${THERMOSTAT_LIBS}/thermostat-launcher-@project.version@.jar"
BOOT_CLASSPATH="${BOOT_CLASSPATH}:${THERMOSTAT_LIBS}/thermostat-main-@project.version@.jar"
BOOT_CLASSPATH="${BOOT_CLASSPATH}:${THERMOSTAT_LIBS}/thermostat-shared-config-@project.version@.jar"

# Append extra class path entries coming from the profiles
if [ ! -z "${THERMOSTAT_EXT_BOOT_CLASSPATH}" ]; then
  BOOT_CLASSPATH="${BOOT_CLASSPATH}:${THERMOSTAT_EXT_BOOT_CLASSPATH}"
fi

function usage() {
    echo "$0 [-J<java-opt>] [-Tbg PIDFILE] [THERMOSTAT_ARGS]" >&2
    exit 1
}

# start parsing arguments, we intercept jvm arguments vs thermostat specific
# arguments
JAVA_ARGS=()
ARGS=()

RUN_IN_BG=0
PID_FILE=""

PATH_TO_SPLASHIMAGE="$THERMOSTAT_HOME/../../packaging/shared/icons/splash-image.png"
i=0
j=0

while [ "$#" -gt "0" ];
do
    case "$1" in
    -J*)
        JAVA_ARGS[$i]="${1##-J}"
        i=$((i+1))
        shift
        ;;
    -Tbg)
        shift
        RUN_IN_BG=1
        PID_FILE="$1"
        shift
        ;;
    *)
        ARGS[$j]="$1"
        if [ $1 = "--show-splash" ] && [ $j > 0 ]; then
            if [ ${ARGS[$j-1]} = "local" ]; then
                JAVA_ARGS+=(-splash:$PATH_TO_SPLASHIMAGE)
            elif [ ${ARGS[$j-1]} = "gui" ] && [ ! -f $USER_THERMOSTAT_HOME/data/splashscreen.stamp ]; then
                JAVA_ARGS+=(-splash:$PATH_TO_SPLASHIMAGE)
            fi
        fi
        j=$((j+1))
        shift
        ;;
    esac
done

# if running on cygwin, modify THERMOSTAT_HOME and BOOT_CLASSPATH to windows for the JDK
if [ $CYGWIN_MODE -eq 1 ]; then
  export THERMOSTAT_HOME="`cygpath -w $THERMOSTAT_HOME`"
  export USER_THERMOSTAT_HOME="`cygpath -w $USER_THERMOSTAT_HOME`"
  BOOT_CLASSPATH=$(cygpath -w -p "$BOOT_CLASSPATH")
  ##env
  # in a VM, jline can cause 100% CPU usage on Windows without this
  THERMOSTAT_EXT_JAVA_OPTS="$THERMOSTAT_EXT_JAVA_OPTS -Djline.terminal=jline.UnsupportedTerminal"
  # in cygwin, the openJDK uses c:\home\user as java.home. which is unhelpful.
  # pass the cygwin home directory instead
  THERMOSTAT_EXT_JAVA_OPTS="$THERMOSTAT_EXT_JAVA_OPTS -Duser.home=`cygpath -w $HOME`"
else
  export THERMOSTAT_HOME
  export USER_THERMOSTAT_HOME
fi

# Finally run thermostat (optionally in the background)
if [ ${RUN_IN_BG} -eq 1 ]; then
    # The thermostat-agent-sysd script uses this.
    if [ x"${PID_FILE}" = "x" ]; then
        usage 
    else
        "${JAVA}" ${THERMOSTAT_EXT_JAVA_OPTS} "${LOGGING_ARGS[@]}" "${JAVA_ARGS[@]}" \
                -cp "${BOOT_CLASSPATH}" \
                ${THERMOSTAT_MAIN} ${THERMOSTAT_EXT_OPTS} "${ARGS[@]}" &
        retval=$?
        echo $! > ${PID_FILE}
        retval=$(( ${retval} + $? ))
    fi
else
    "${JAVA}" ${THERMOSTAT_EXT_JAVA_OPTS} "${LOGGING_ARGS[@]}" "${JAVA_ARGS[@]}" \
            -cp "${BOOT_CLASSPATH}" \
            ${THERMOSTAT_MAIN} ${THERMOSTAT_EXT_OPTS} "${ARGS[@]}"
    retval=$?
fi
exit ${retval}

