#!/bin/bash
#
# Copyright 2012 Red Hat, Inc.
#
# This file is part of Thermostat.
#
# Thermostat is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2, or (at your
# option) any later version.
#
# Thermostat is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Thermostat; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.
#
# Linking this code with other modules is making a combined work
# based on this code.  Thus, the terms and conditions of the GNU
# General Public License cover the whole combination.
#
# As a special exception, the copyright holders of this code give
# you permission to link this code with independent modules to
# produce an executable, regardless of the license terms of these
# independent modules, and to copy and distribute the resulting
# executable under terms of your choice, provided that you also
# meet, for each linked independent module, the terms and conditions
# of the license of that module.  An independent module is a module
# which is not derived from or based on this code.  If you modify
# this code, you may extend this exception to your version of the
# library, but you are not obligated to do so.  If you do not wish
# to do so, delete this exception statement from your version.
#
#####################################################################
#
# Some necessary variables.
if [ "$THERMOSTAT_HOME" = "" ]; then
    echo "THERMOSTAT_HOME not set!"

else
    THERMOSTAT_STORAGE="${THERMOSTAT_HOME}/storage/db"
    THERMOSTAT_LOG="${THERMOSTAT_HOME}/storage/logs"
    THERMOSTAT_PID="${THERMOSTAT_HOME}/storage/run"
    THERMOSTAT_BACKEND="${THERMOSTAT_HOME}/backends/system"
    THERMOSTAT_BIN="${THERMOSTAT_HOME}/bin"
    THERMOSTAT_AGENT_LOG="${THERMOSTAT_HOME}/agent/logs"
    THERMOSTAT_AGENT_RUN="${THERMOSTAT_HOME}/agent/run"
    THEMROSTAT_CLIENT="${THERMOSTAT_HOME}/client"
    THERMOSTAT_LIBS="${THERMOSTAT_HOME}/libs"

    echo "creating $THERMOSTAT_STORAGE"
    mkdir -p $THERMOSTAT_STORAGE
    
    echo "creating $THERMOSTAT_LOG"
    mkdir -p $THERMOSTAT_LOG
    
    echo "creating $THERMOSTAT_PID"
    mkdir -p $THERMOSTAT_PID
    
    echo "creating $THERMOSTAT_BACKEND"
    mkdir -p $THERMOSTAT_BACKEND
    
    echo "creating $THERMOSTAT_BIN"
    mkdir -p $THERMOSTAT_BIN
    
    echo "creating $THERMOSTAT_AGENT_LOG"
    mkdir -p $THERMOSTAT_AGENT_LOG
    
    echo "creating $THERMOSTAT_AGENT_RUN"
    mkdir -p $THERMOSTAT_AGENT_RUN

    echo "creating $THERMOSTAT_CLIENT"
    mkdir -p "$THERMOSTAT_CLIENT"

    echo "creating $THERMOSTAT_LIBS"
    mkdir -p $THERMOSTAT_LIBS
fi
