#!/bin/bash
#
# Copyright 2012-2014 Red Hat, Inc.
#
# This file is part of Thermostat.
#
# Thermostat is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2, or (at your
# option) any later version.
#
# Thermostat is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Thermostat; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.
#
# Linking this code with other modules is making a combined work
# based on this code.  Thus, the terms and conditions of the GNU
# General Public License cover the whole combination.
#
# As a special exception, the copyright holders of this code give
# you permission to link this code with independent modules to
# produce an executable, regardless of the license terms of these
# independent modules, and to copy and distribute the resulting
# executable under terms of your choice, provided that you also
# meet, for each linked independent module, the terms and conditions
# of the license of that module.  An independent module is a module
# which is not derived from or based on this code.  If you modify
# this code, you may extend this exception to your version of the
# library, but you are not obligated to do so.  If you do not wish
# to do so, delete this exception statement from your version.
#
#####################################################################
#
# for debugging
#set -xv

if [ $# -ne 1 ]; then
    echo "usage: $0 {start|stop|restart}" >&2
    exit 1
fi

if [ x"$THERMOSTAT_HOME" = x ] ; then
    THERMOSTAT_HOME="@thermostat.home@"
fi

export THERMOSTAT_HOME
THERMOSTAT_BIN="$THERMOSTAT_HOME/bin/thermostat"
AGENT_PID_FILE="$THERMOSTAT_HOME/run/thermostat-agent.pid"

function start() {
    if [ -e "$AGENT_PID_FILE" ]; then
        echo "Agent already running. Use '$0 stop' to stop it." >&2
        exit 1
    fi
    # This writes PID of java process to AGENT_PID_FILE
    "$THERMOSTAT_BIN" -Tbg "$AGENT_PID_FILE" agent
    exit $?
}

function stop() {
    if [ -e "$AGENT_PID_FILE" ]; then
        pid=$(cat "$AGENT_PID_FILE")
        kill $pid
        retval=$?
        # cleanup pid
        rm -rf "$AGENT_PID_FILE"
        exit $retval
    else
        exit 1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
esac

